version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  embedding-service:
    build:
      context: ./embedding_service
    ports:
      - "6000:6000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - embedding-service

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
